### ISSUE TITLE
Initial sync is failing, something about a folder name

### ISSUE THREAD

**Issue by mranders** [christopherjwhite/org-toodledo#1]
I was just trying to do the org-toodledo-initialize, and it quit with an error, I see two TODO's.  Any idea how to figure out what it is complaining about?

No heading found matching 'TASKS', create? (y or n)
Contacting host: api.toodledo.com:443
Opening TLS connection to `api.toodledo.com'...
Opening TLS connection with`gnutls-cli -p 443 api.toodledo.com'...failed
Opening TLS connection with `gnutls-cli -p 443 api.toodledo.com --protocols ssl3'...failed
Opening TLS connection with`openssl s_client -connect api.toodledo.com:443 -no_ssl2 -ign_eof'...done
Opening TLS connection to `api.toodledo.com'...done
Reading [application/xml]... 710 bytes of 701 bytes (101%)
Contacting host: api.toodledo.com:80
Reading [application/xml]... 59 bytes of 50 bytes (118%)
if: Call to folders/add failed: Your folder must have a name

**Comment by mranders** [comment]
Hmmm, I apparently only had a "Folder" for one task, and once I removed that, it synced fine.

Not the most intuitive, but perhaps the Folder handling could be improved?

**Comment by christopherjwhite** [comment]
Hmm... it looks like it was trying to create a folder on the server and
that call failed.  Can I ask, were you initializing with tasks already
in the org-mode buffer, or was the org-mode buffer empty and it was
just importing tasks from toodledo.com?

I get that error when I try to create a folder with an empty name via
the manual call:

 (org-toodledo-folder-to-id "")

In the tasks that you have in the buffer, can you open the properties
drawer of each task (put the cursor on the ":PROPERTIES:" line in the
task and hit tab) -- do you see a line with ":FOLDER:" in it?  If so,
what is value?  And what do you get back when you do:

  M-x eval-expression (org-entry-get nil "FOLDER")

Finally -- can you tell me what version of emacs and org you are using:

  M-x emacs-version
  M-x org-version

Let's see if any of that helps -- if not I'll have to put some debug
statements in the code to figure out what's going on!

Thanks
...cj

org-toodledo uses tags that start with an "@" as the 

On Thu, 6 Oct 2011 09:36:43 -0700
mranders
reply@reply.github.com
wrote:

> I was just trying to do the org-toodledo-initialize, and it quit with
> an error, I see two TODO's.  Any idea how to figure out what it is
> complaining about?
> 
> No heading found matching 'TASKS', create? (y or n)
> Contacting host: api.toodledo.com:443
> Opening TLS connection to `api.toodledo.com'...
> Opening TLS connection with`gnutls-cli -p 443
> api.toodledo.com'...failed Opening TLS connection with `gnutls-cli -p
> 443 api.toodledo.com --protocols ssl3'...failed Opening TLS
> connection with`openssl s_client -connect api.toodledo.com:443
> -no_ssl2 -ign_eof'...done Opening TLS connection to
> `api.toodledo.com'...done Reading [application/xml]... 710 bytes of
> 701 bytes (101%) Contacting host: api.toodledo.com:80 Reading
> [application/xml]... 59 bytes of 50 bytes (118%) if: Call to
> folders/add failed: Your folder must have a name

**Comment by mranders** [comment]
On Oct 6, 2011 8:10 PM, "Christopher J. White" <
reply@reply.github.com>
wrote:

> Hmm... it looks like it was trying to create a folder on the server and
> that call failed.  Can I ask, were you initializing with tasks already
> in the org-mode buffer, or was the org-mode buffer empty and it was
> just importing tasks from toodledo.com?

Just importing tasks from toodledo.com. I am a newbie when it comes to
org-mode, but I live in emacs quite a bit. I thought if perhaps I brought
ToodleDo into my emacs lifestyle then I could make better use GTD and
ToodleDo.  And then I might be able to have a useful list of things I need
to accomplish synced with my phone.

Since I was able to sync the tasks once I removed the only Folder in
ToodleDo, I just moved the single task back into the only folder "Auto" and
the org-toodledo interface doesn't capture it correctly.  It finds the
folder on the server, but it calls the folder the empty string.
- TASKS
  :PROPERTIES:
  :ToodledoLastSync: 0
  :END:
  *\* TODO [#C] Exercise :@Home:
    SCHEDULED: <2011-06-04 Sat .+1w>
  :PROPERTIES:
  :ToodledoID: 521876
  :Modified: 1306616707
  :Sync:     1317969857
  :Effort:   0
  :Hash:     0687e21139275b442cab718a75ef3e80
  :END:
  *\* TODO [#C] Little car tires :@Home:
  :PROPERTIES:
  :ToodledoID: 541544
  :Modified: 1317969829
  :Folder:
  :Sync:     1317969857
  :Effort:   0
  :END:

Perhaps this gives you some clues to go on.

GNU Emacs 23.2.1 (i686-pc-linux-gnu, GTK+ Version 2.24.4) of 2011-04-04 on
rothera, modified by Debian
Org-mode version 6.33x

> I get that error when I try to create a folder with an empty name via
> the manual call:
> 
>  (org-toodledo-folder-to-id "")
> 
> In the tasks that you have in the buffer, can you open the properties
> drawer of each task (put the cursor on the ":PROPERTIES:" line in the
> task and hit tab) -- do you see a line with ":FOLDER:" in it?  If so,
> what is value?  And what do you get back when you do:
> 
>  M-x eval-expression (org-entry-get nil "FOLDER")

I get "" when I evaluate this expression on that TODO entry.

**Comment by christopherjwhite** [comment]
This is good info!  I was able to reproduce it with your version of
org-mode.  There appear to be 2 problems, one not getting/setting the
Folder properly on import, and then later returning "" instead of nil
when the folder is empty (an org-mode change...)

Both should be easy enough to fix...I'll get back to you!

...cj

On Thu, 6 Oct 2011 23:52:34 -0700
mranders
reply@reply.github.com
wrote:
