### ISSUE TITLE
org-version not defined? (with org-mode 7.9)

### ISSUE THREAD

**Issue by BeSlayed** [christopherjwhite/org-toodledo#11]
This perhaps is just an issue with my install, I'm not sure. But it seems that since I upgraded to the newest org-mode (from git) that org-toodledo complains that it can't find the org-version variable, and won't sync.

The workaround that fixes this, for me, is to add to my .emacs:

(require 'org-version)
(setq org-version (org-release))

**Comment by christopherjwhite** [comment]
I found some info on the org mailing list regarding this:

http://thread.gmane.org/gmane.emacs.orgmode/59337
http://comments.gmane.org/gmane.emacs.orgmode/55412

So this looks like an org installation issue.  Can you try some of the 
solutions listed above and see if that resolves the problem?

If not, sounds like you should post the problem to org-mode.

...cj

**Comment by BeSlayed** [comment]
## Thanks, I'll try that.

Benjamin Slade slade@uta.edu slade@uta.edu
Dept. of Linguistics & TESOL
University of Texas at Arlington
[ http://www.jnanam.net/slade/ ]

132E Hammond Hall | Office Hours: TBA

## Stæfcræft & Vyākaraṇa (lingblog) - http://staefcraeft.blogspot.com

  _प_रो ऽक्ष॑का_मा_ हि _दे_वाः

##     'The gods love the obscure.' (Śatapathabrāhmaṇa 6.1.1.2)

---

Choose freedom, choose GNU http://www.gnu.org/ &
Linuxhttp://www.whylinuxisbetter.net/
.

**Comment by christopherjwhite** [comment]
Closing this for now, I think this should have been resolved by the org team.
