### ISSUE TITLE
error on sync

### ISSUE THREAD

**Issue by rkrug** [christopherjwhite/org-toodledo#15]
Hi

I just installed org-toodledo via elpa and I get an error upon the first sync. The messages are below:

Starting org-toodledo-sync
No heading found matching 'TASKS', create? (y or n)  y
Starting org-toodledo-sync
org-toodledo buffer at latest version 2.10
Contacting host: api.toodledo.com:80
Server has changes, asking for all modafter="0"
Contacting host: api.toodledo.com:80 [2 times]
if: Symbol's function definition is void: org-export-remove-or-extract-drawers

I am using org-toodledo version 20130324.1837 and Org-mode version 8.0-pre (release_8.0-pre-473-gf20de0 @ /home/rkrug/.emacs.d/org-mode/lisp/) from git.

Any suggestions what I can do?

Thanks,

Rainer

**Comment by dreki** [comment]
I get this as well. Breaks sync altogether.

**Comment by christopherjwhite** [comment]
What version of org-mode are you using?  Version 7 changed the argument list for the function org-export-remove-or-extract-drawers, but I have not seen any problems with that function disappearing altogether.  Can one of you try to find out of if your version of org has that function defined somewhere, and if so, what file it's in?

**Comment by alexvorobiev** [comment]
The function org-export-remove-or-extract-drawers was part of the old exporter which was removed in v.8

**Comment by christopherjwhite** [comment]
I tested with org 8.0.3 and the latest update should take care of this issue.  Let me know if you still see a problem, thanks!
