### ISSUE TITLE
clock-in with prefix starts org-toodledo-initialize on intialized file

### ISSUE THREAD

**Issue by steckerhalter** [christopherjwhite/org-toodledo#16]
from the org manual:

```
C-c C-x C-i org-clock-in

When called with a C-u prefix argument, select the task from a list of
recently clocked tasks.
```

When I do this `org-toodledo-initialize` is called and asks me for the "Default heading for Toodledo tasks" even though Toodledo is initialized already.

Am I misunderstanding something here?

**Comment by christopherjwhite** [comment]
I can't reproduce this in my setup (org 7.8.03 on Emacs 24.3.1).  What version of org and emacs are you running?

Can you try and get a backtrace?

  M-x debug-on-entry org-toodledo-initialize

This should give you trace of why it's getting there.

**Comment by steckerhalter** [comment]
Oh, debug-on-entry is pretty cool. Didn't know that. Anyway. I can't reproduce it either now. I'll close the report. Thanks.

**Comment by steckerhalter** [comment]
Looks like you have to close it then :)

**Comment by christopherjwhite** [comment]
Sounds good, let me know if it crops up again.
