### ISSUE TITLE
Debugging http-post-simple.el for use with Emacs Trunk 24.3.50 (9.0).

### ISSUE THREAD

**Issue by lawlist** [christopherjwhite/org-toodledo#18]
I have a request for help open on stackoverflow to debug http-post-simple-el for use with Emacs Trunk 24.3.50 (9.0).

```
 (lambda (field) ...) quoted with ' rather than with #'
```

http://stackoverflow.com/questions/17285048/http-post-simple-el-lambda-field-quoted-with-rather-than-with

If I find an answer, I'll let you know.  If you have any ideas, that would be great.

**Comment by lawlist** [comment]
You may also wish to consider adding a notation to your readme documentation of an error when starting emacs caused by an inability to locate a function within mailcap.elc.  

```
Symbol’s function definition is void: mailcap-parse-mailcaps
```

I fixed the error by manually calling it:

(load-file ". . . /Emacs.app/Contents/Resources/lisp/gnus/mailcap.elc")

**Comment by lawlist** [comment]
"phils" on stackoverflow fixed http-post-simple.el by recommending that the single quotes be removed from each reference to (lambda (field) ... -- there are five (5) single quotes that need to be removed.  You may want to make a notation on your readme file on how to fix http-post-simple.el for current versions of Emacs.

**Comment by christopherjwhite** [comment]
Added comment to the installation instructions

**Comment by lawlist** [comment]
Thank you.  :)
