### ISSUE TITLE
missing require

### ISSUE THREAD

**Issue by jefftemplon** [christopherjwhite/org-toodledo#2]
Hi,

I got errors that the function 'aput' was unknown.  I solved this by adding the line (require 'assoc) below:

(require 'http-post-simple)
(require 'url)
(require 'url-http)
(require 'assoc)
;;
;; User customizable variables
;;

JT

**Comment by christopherjwhite** [comment]
Heh -- good one, I must have so many other lisp files loaded before
this one that I never hit it.  Thanks, I'll put this in a quick patch!

...cj

On Wed, 2 Nov 2011 08:01:18 -0700
jefftemplon
reply@reply.github.com
wrote:

> Hi,
> 
> I got errors that the function 'aput' was unknown.  I solved this by
> adding the line (require 'assoc) below:
> 
> (require 'http-post-simple)
> (require 'url)
> (require 'url-http)
> (require 'assoc)
> ;;
> ;; User customizable variables
> ;;
> 
> JT
