### ISSUE TITLE
Unable to synchronize all completed todo on the Toodledo server.

### ISSUE THREAD

**Issue by lawlist** [christopherjwhite/org-toodledo#26]
The most recent two versions of `org-toodledo.el` do not appear to have the ability to synchronize _all_ completed todo on the Toodledo server.  I reverted back  to version 2.11 in order to re-enable that behavior.

If a user has completed tasks on the Toodledo server and a _blank_ org file, then _none_ of the completed tasks will synchronize to the org file using a current version of `org-toodledo.el`.  Only after the org file has been synchronized with the Toodledo server, will subsequently completed tasks on Toodledo synchronize back to the org file.  The tasks that were completed prior to the first synchronization with the org file will _not_ synchronize to the org file.

**Comment by christopherjwhite** [comment]
Did you try setting org-toodledo-sync-new-completed-tasks to t?  This 
defaults to nil.  However, it's been there since long before 2.10, so 
I'm not sure why it would work in 2.10 and not in newer releases...

...cj

**Comment by lawlist** [comment]
It is line 993:

```
(alist-put params "comp" (if init "0" "-1"))
```

Instead of:

```
(alist-put params "comp" "-1")
```

Some users may prefer that their org file match the server exactly -- i.e., all tasks whether completed or not.  With line 993 the way it is now `(if init "0" "-1")`, users _cannot_ have `org-toodledo-sync` populate a blank org file with everything on the server.  If users wish to exclude completed tasks, either on the _initial_ or _subsequent_ synchronization, perhaps this could be a user defined variable -- otherwise, source code modification by the user would be required.

**Comment by christopherjwhite** [comment]
Got it, I changed this to:

```
(alist-put params "comp" (if (or init org-toodledo-sync-new-completed-tasks) "0" "-1"))
```

Will check in with other fixes / changes.

**Comment by christopherjwhite** [comment]
My comment above was incorrect -- the correct fix is:

```
(alist-put params "comp" (if (and init (not org-toodledo-sync-new-completed-tasks)) "0" "-1"))
```

Committed.
