### ISSUE TITLE
"no such file or directory" "org-toodledo-test"

### ISSUE THREAD

**Issue by steckerhalter** [christopherjwhite/org-toodledo#32]
``` lisp
(file-error "Cannot open load file" "no such file or directory" "org-toodledo-test")
  require(org-toodledo-test)
```

latest version from MELPA can't be loaded because of this error.
I tried reinstalling but that didn't help

**Comment by bradyt** [comment]
I had the same problem. I downloaded the file and placed it into the org-toodledo directory and it worked fine.

**Comment by christopherjwhite** [comment]
Yep -- seems MELPA doesn't include the test or sim files in it's package.  I have removed the direct dependency and only require it if you try to run the tests.
