### ISSUE TITLE
Setup Emacs for use w/ & wo/ Toodledo

### ISSUE THREAD

**Issue by DSMasterson** [christopherjwhite/org-toodledo#37]
Need documentation on how to setup org-toodledo such that you can have an Org file that will sync with Toodledo _AND_ an Org file that will not be synced with Toodledo if that is possible.  This is especially important for transitioning from one to the other as you may want to move some tasks over, but keep others in the old setup while you test out the new capabilities.

**Comment by christopherjwhite** [comment]
Hey David

'org-toodledo' pretty much has tunnel vision when it comes to synchronization.  When you run 'org-toodledo-sync', this scans the current buffer only.  If this buffer has not been initialized (it doesn't see any traces of Toodledo synchronization), then it sets up the buffer with a few tags in an org-entry (TASKS by default).  Sync then just looks at all TODO entries in that buffer.

As such, you can have as many org files as you like.  It (currently) really only makes sense to have one org file that is set up to sync with Toodledo.

That said, org-toodledo will archive entries to another org file on completion.   See the README, as this has documentation about this feature.

All org related features for moving TODO entries from one org file to another will work just fine.  org-sync, however, will only look at TODO entries in the current buffer.  So, consider a TODO entry in the org-toodledo-synced buffer "todo.org", and it is synced with Toodledo.  If you move that TODO entry to another file (say "other.org")(, then go back to the to "todo.org" and sync, it will recreate that entry from the copy on Toodledo.

Note that at any time you can open up a new empty buffer and call org-toodledo-initialize.  This will pull in all active tasks from your Toodledo account on the server.  It will have no relationship with any other org files that you may have previously synced with Toodledo.

The test framework in org-toodledo-test relies on this behavior as it creates todo entries in one buffer, syncs them to the server, then switches to another buffer and syncs them from the server.  Two buffers like this is essentially the same has having multiple completely separate clients attempting to make changes to the TODO entries simultaneously.

Going to close this for now, as I think I've provided the information you need.  Feel free to reopen if you need additional info.

**Comment by DSMasterson** [comment]
That is a lot of what I was looking for.  The only thing I would suggest is
moving much of what you said into the README file for org-toodledo to help
people understand where org-toodledo and org don't quite line up.  The only
other thing I'd suggest is to add to the INSTALLATION section of the README
information on how to use Git to pull in the latest copy of org-toodledo (a
quick example should be enough).

What are your plans for org-toodledo?  Perhaps an org-toodledo-files (a la
org-agenda-files) that could be scanned for TODOs to sync with Toodledo?
In this way, the user could have separate Org files for each project rather
than lump all TODOs into one file.  You'd probably need a (file-specific?)
setting to say only sync TODOs into a file that are already in the file.

On Sun, Mar 30, 2014 at 8:35 AM, Christopher J. White <
notifications@github.com> wrote:

> Hey David
> 
> 'org-toodledo' pretty much has tunnel vision when it comes to
> synchronization. When you run 'org-toodledo-sync', this scans the current
> buffer only. If this buffer has not been initialized (it doesn't see any
> traces of Toodledo synchronization), then it sets up the buffer with a few
> tags in an org-entry (TASKS by default). Sync then just looks at all TODO
> entries in that buffer.
> 
> As such, you can have as many org files as you like. It (currently) really
> only makes sense to have one org file that is set up to sync with Toodledo.
> 
> That said, org-toodledo will archive entries to another org file on
> completion. See the README, as this has documentation about this feature.
> 
> All org related features for moving TODO entries from one org file to
> another will work just fine. org-sync, however, will only look at TODO
> entries in the current buffer. So, consider a TODO entry in the
> org-toodledo-synced buffer "todo.org", and it is synced with Toodledo. If
> you move that TODO entry to another file (say "other.org")(, then go back
> to the to "todo.org" and sync, it will recreate that entry from the copy
> on Toodledo.
> 
> Note that at any time you can open up a new empty buffer and call
> org-toodledo-initialize. This will pull in all active tasks from your
> Toodledo account on the server. It will have no relationship with any other
> org files that you may have previously synced with Toodledo.
> 
> The test framework in org-toodledo-test relies on this behavior as it
> creates todo entries in one buffer, syncs them to the server, then switches
> to another buffer and syncs them from the server. Two buffers like this is
> essentially the same has having multiple completely separate clients
> attempting to make changes to the TODO entries simultaneously.
> 
> Going to close this for now, as I think I've provided the information you
> need. Feel free to reopen if you need additional info.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/christopherjwhite/org-toodledo/issues/37#issuecomment-39028469
> .

## 

David Masterson
Programmer at Large
