### ISSUE TITLE
sync fails because GnuTLS hangs

### ISSUE THREAD

**Issue by cmchittom** [christopherjwhite/org-toodledo#6]
I'm using&mdash;or rather, trying to use&mdash;org-toodledo with Emacs 23.3 and Org 7.7 on Windows XP.  The Windows-native GnuTLS is installed and in the PATH.  Even though `org-toodledo-use-https` is `nil` and `org-toodledo-inhibit-https` is `t`, `M-x org-toodledo-initialize` and `M-x org-toodledo-sync` still try to to use TLS and/or SSL via GnuTLS, which fails because GnuTLS hangs.  Moving GnuTLS out of the PATH and trying again gives me the error `Wrong type argument: processp, nil` in the minibuffer.

**Comment by christopherjwhite** [comment]
This is getting into the http code, which I have only barely looked at and fixed just one issue I found with https.  I can't quite explain what it's doing.  

Can you try the latest version and enable debug by `M-x org-toodledo-toggle-debug`, then try syncing.  If (when?) it fails, take a look at the buffer `*Org-toodledo-debug*` and send me whatever you can (scan it for personal info).

If you're adventurous and good with emacs, you can try stepping into the http code, but this gets pretty tough to follow.

**Comment by christopherjwhite** [comment]
This should be fixed in 2.5 release.  I was still using https for retrieving the login token even though inhibit-https was set.
